<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title><?php echo $heading ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->config->item('base_header_path'); ?>view.css" media="all">
<script type="text/javascript" src="<?php echo $this->config->item('base_header_path'); ?>view.js"></script>
<script type="text/javascript" src="<?php echo $this->config->item('base_header_path'); ?>calendar.js"></script>
</head>
<body id="main_body" >
	
	<img id="top" src="<?php echo $this->config->item('base_header_path'); ?>top.png" alt="">
	<div id="form_container">
	
		<h1><a>Hisaab Kitaab</a></h1>
		<form id="form_287693" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Hisaab Kitaab</h2>
			<p>362-F2,Gaur Homes.Ghaziabad</p>
		</div>						
			<ul >
			
					<li id="li_4" >
		<label class="description" for="element_4">Your Name? </label>
		<div>
		<select class="element select medium" id="element_4" name="element_4"> 
			<option value="" selected="selected"></option>
<option value="1" >Anand Kumar Chaudhary</option>
<option value="2" >Shiva Gupta</option>
<option value="3" >Shivendra Verma</option>
<option value="4" >Akash Srivastava</option>
<option value="5" >Rajan Tiwari</option>

		</select>
		</div><p class="guidelines" id="guide_4"><small>Please select the name of the person who have made the payment.</small></p> 
		</li>		<li id="li_1" >
		<label class="description" for="element_1">Date </label>
		<span>
			<input id="element_1_1" name="element_1_1" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="element_1_1">MM</label>
		</span>
		<span>
			<input id="element_1_2" name="element_1_2" class="element text" size="2" maxlength="2" value="" type="text"> /
			<label for="element_1_2">DD</label>
		</span>
		<span>
	 		<input id="element_1_3" name="element_1_3" class="element text" size="4" maxlength="4" value="" type="text">
			<label for="element_1_3">YYYY</label>
		</span>
	
		<span id="calendar_1">
			<img id="cal_img_1" class="datepicker" src="<?php echo $this->config->item('base_header_path'); ?>calendar.gif" alt="Pick a date.">	
		</span>
		<script type="text/javascript">
			Calendar.setup({
			inputField	 : "element_1_3",
			baseField    : "element_1",
			displayArea  : "calendar_1",
			button		 : "cal_img_1",
			ifFormat	 : "%B %e, %Y",
			onSelect	 : selectDate
			});
		</script>
		<p class="guidelines" id="guide_1"><small>Please select the date when the payment was made.</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Description </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_2"><small>Short description for the item bought</small></p> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Amount </label>
		<div>
			<input id="element_3" name="element_3" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_3"><small>Enter the amount of payment in INR.</small></p> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="287693" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://itspectrum.co.in">IT SPECTRUM</a>
		</div>
	</div>
	<img id="bottom" src="<?php echo $this->config->item('base_header_path'); ?>bottom.png" alt="">
	</body>
</html>